name: release-main

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Setup pnpm 📦
        run: npm i -g pnpm@8.9.2

      - name: Install dependencies 📦
        run: pnpm i -r

      - name: Install semantic-release extra plugins 📦
        run: pnpm install --save-dev @semantic-release/changelog @semantic-release/git

      - name: Run linter 👀
        run: pnpm run lint-fix

      - name: Typecheck 👀
        run: pnpm run typecheck

      - name: Run tests 🧪
        run: pnpm run test:unit

      - name: Build
        run: pnpm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
